version: '3.8'
services:
  server:
    build:
      context: ./node-admin
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '8000:8000'
    volumes:
      - ./node-admin/node_modules:/app/node_modules
      - ./node-admin:/app

  npm:
    build:
      context: ./node-admin
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./node-admin:/app
      - ./node-admin/node_modules:/app/node_modules
