version: '3.8'
services:
  server:
    build:
      context: ./node-admin
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '8000:8000'
    volumes:
      - ./node-admin/node_modules:/app/node_modules
      - ./node-admin:/app
    depends_on:
      - db
  front:
    build:
      context: ./vue-admin
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=developement
    ports:
      - '8080:8080'
    volumes:
      - ./vue-admin/node_modules:/app/node_modules
      - ./vue-admin:/app
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - ./db/mysql.env
    volumes:
      - data1:/var/lib/mysql
      - ./db:/etc/mysql/sql

  npm:
    build:
      context: ./node-admin
      # context: ./vue-admin
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./node-admin:/app
      - ./node-admin/node_modules:/app/node_modules
      # - ./vue-admin:/app
      # - ./vue-admin/node_modules:/app/node_modules

  vue-create:
    build:
      context: ./vue-admin
      dockerfile: Dockerfile
    working_dir: /app
    command: vue create .
    volumes:
      - ./vue-admin:/app
      - ./vue-admin/node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  data1:
